### ISSUE TITLE
The kernel "pinned commit" mismatch

### ISSUE THREAD

**Issue by astsam** [sehraf/riscv-arch-image-builder#1]
The script 1_compile.sh silently stops after cloning kernel. The script assumes that kernel top commit in the branch riscv/d1-wip is the "pinned commit". That is wrong and the script silently stops. Actually the "pinned commit" has a tag d1-wip-v5.18-rc1. [This patch may fix the issue](https://gist.github.com/astsam/56b1a6094c5b1d1d46c1f0e6742aa615).

**Comment by sehraf** [comment]
Ah, i wasn't aware of the `d1-wip-v5.18-rc1` tag, thanks for pointing this out.
I've changed the code to use this tag for now (i tried the rebase on `-rc4` but that resulted in a kernel panic)

**Comment by sehraf** [comment]
Fixed in cd6efcb55a17c98b2987abf3b81fe4efb394cc34
