### ISSUE TITLE
success on Sipeed Lichee RV Dock rv64imafdc

### ISSUE THREAD

**Issue by davidoccam** [sehraf/riscv-arch-image-builder#10]
Thank you and your collaborators for your excellent work

[root@licheerv ~]#  timedatectl status
               Local time:        Sun 2022-07-31 14:59:38 UTC
               Universal time:  Sun 2022-07-31 14:59:38 UTC
              RTC time:           Sun 2022-07-31 14:59:06
              Time zone: UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
              RTC in local TZ: no
[root@licheerv ~]# neofetch

OS: Arch Linux riscv64 
Host: Sipeed Lichee RV Dock 
Kernel: 5.19.0-rc1-gfe178cf0153d-dirty 
Uptime: 20 mins 
Packages: 756 (pacman) 
Shell: bash 5.1.16 
Resolution: 1280x1024 
Terminal: /dev/ttyS0 
CPU: (1) 
Memory: 46MiB / 483MiB 

got wifi and nano editor working by installing 

 dhclient-4.4.3-1-riscv64.pkg.tar.zst
 dhcpcd-9.4.1-1-riscv64.pkg.tar.zst
'dialog-1 1.3_20220526-1-riscv64.pkg.tar.zst'
 ell-0.51-1-riscv64.pkg.tar.zst
 glibc-2.35-2.1-riscv64.pkg.tar.zst
 ifplugd-0.28-16-riscv64.pkg.tar.zst
 iwd-1.28-1-riscv64.pkg.tar.zst
 libdaemon-0.14-5-riscv64.pkg.tar.zst
 nano-6.3-1-riscv64.pkg.tar.zst
 ncurses-6.3-3-riscv64.pkg.tar.zst
 netctl-1.28-1-any.pkg.tar.zst
 run-parts-5.5-1-riscv64.pkg.tar.zst
 systemd-resolvconf-251.3-1-riscv64.pkg.tar.zst
 wireless_tools-30.pre9-3-riscv64.pkg.tar.zst
'wpa_supplicant-2 2.10-4-riscv64.pkg.tar.zst'

from https://archriscv.felixc.at/
via usb disk 

copied modules from        /lib/modules/5.19.0-AllWinnerD1-Smaeul
to  (uname -r)                   /lib/modules/5.19.0-rc1-gfe178cf0153d-dirty

depmod
lsmod 8723ds

wifi-menu to start wifi with credentials
then pacman -Syu to perform full update

thank you again
if I can test anything on a Sipeed Lichee RV Dock

cat /proc/cpuinfo
processor	: 0
hart		: 0
isa		: rv64imafdc
mmu		: sv39
uarch		: thead,c906

I am happy to help.

**Comment by kassane** [comment]
If you want you can try this:
- #11

**Comment by hyx0329** [comment]
To fully get rid of kernel version issue, the script shouldn't rely on a constant value as the code below:

https://github.com/sehraf/riscv-arch-image-builder/blob/c148ec31c3d78606460154f290a848b6a085d2da/consts.sh#L44

https://github.com/sehraf/riscv-arch-image-builder/blob/c148ec31c3d78606460154f290a848b6a085d2da/2_create_sd.sh#L87

Instead, use `make kernelversion` to generate the actual kernel version string when installing the modules. For example:

```
# get kernel version, eg. "5.19.0-rc1"
RELEASE_PREFIX=$(make -C ${BUILD_DIR} -s kernelversion)
# the suffix, eg. "-AllWinnerD1-Smaeul"
RELEASE_SUFFIX="-what-defined-as-CONFIG_LOCALVERSION"
KERNEL_RELEASE=${RELEASE_PREFIX}${RELEASE_SUFFIX}
make ARCH="${ARCH}" INSTALL_MOD_PATH="../../${MNT}" KERNELRELEASE="${KERNEL_RELEASE}" modules_install
```

BTW my implementation is here:

https://github.com/hyx0329/riscv-archlinux-d1/blob/535ff16a73ecbe0575a1f7bc7b247d83af010e94/linux/Makefile#L113
