### ISSUE TITLE
Oreboot + LinuxBoot

### ISSUE THREAD

**Issue by kassane** [sehraf/riscv-arch-image-builder#13]
Hi @sehraf,

I am suggesting a possible alternative usage allowing the user to decide and contribute other tools.
Perhaps by making the script more interactive or by assigning a new implementation separate from the original script.

Do you have something to suggest?
@orangecms

https://gist.github.com/orangecms/df0d3c15f9e32b5c708c021c4be8857b

**Comment by orangecms** [comment]
I think the goals here are different. This script here builds a monolithic image, whereas with oreboot + LinuxBoot, you would get a versatile, interactive boot environment in firmware that allows for loading any OS from any media/storage, including SD card, USB, network, or whatever.
In other words, with LinuxBoot, there is no need to do anythig further. You only put it on a SPI flash, and then you are fully flexible. Put anything on your media as you like.

In the other hand, a full image (such as built by this repo) is specific to
- the SoC, the ISA and the vendor
- the board with its attached and included peripherals
- a given distro, potentially with a specific environment/configuration

There are many combinations possible with those dimensions alone.

**Comment by sehraf** [comment]
Hi, 
@orangecms summed things up pretty well.

My main motivation behind these scripts was to a) understand and b) reproduce a bootable image. 
_My existing ARM boards  boot with a "existing boot setup" copied from random images - i neither understand it nor can i update/reproduce it. I can change kernel/initramfs/dtb filenames, at max_ :roll_eyes:

While i do love rust :crab:, i don't see any advantage (worth it) over u-boot. I wish i could select a kernel when booting, maybe chainloading grub (like Fedora does/did?) or even systemd-boot (is EFI a thing on the D1?) is an idea.
Right now it doesn't even work with the current 5.19 kernel :man_shrugging: 

I'll close the issue but feel free to continue discussing.

**Comment by orangecms** [comment]
What you can do is to add LinuxBoot with u-root on top of U-Boot, and that replaces GRUB, systemd-boot etc altogether. There is no need for (U)EFI.

You can then just use the `localboot` command for the init, and you'll be presented with a boot menu listing everything resulting from probing local storages. With https://github.com/u-root-webboot, you can boot arbitrary distros from the web (hence the name).
