### ISSUE TITLE
qemu-user-static-bin and binfmt-qemu-static appear to have been deleted from AUR

### ISSUE THREAD

**Issue by wezm** [sehraf/riscv-arch-image-builder#15]
* `binfmt-qemu-static-all-arch` can be used as a replacement for `binfmt-qemu-static`
* For now `qemu-user-static-bin` can still be installed by cloning the repo and building it:
  * `git clone https://aur.archlinux.org/qemu-user-static-bin.git`

**Comment by sehraf** [comment]
#feelsBadMan also why?!
Thanks for the heads up!

**Comment by kassane** [comment]
[PKGBUILD_qemu-user-static-bin.tar.gz](https://github.com/sehraf/riscv-arch-image-builder/files/9540425/PKGBUILD_qemu-user-static-bin.tar.gz)
[PKGBUILD_binfmt-qemu-static.tar.gz](https://github.com/sehraf/riscv-arch-image-builder/files/9540426/PKGBUILD_binfmt-qemu-static.tar.gz)

**Comment by kassane** [comment]
Today: :disappointed: 
```bash
binfmt-qemu-static-all-arch was not found in AUR -- skipping
```

**Comment by kassane** [comment]
@sehraf, I don't know if you want to use docker to generate the image.
However, an interesting approach has emerged of creating a `riscv64/linux` image using docker+QEMU+binfmt.

Ref.: https://www.docker.com/blog/multi-platform-docker-builds/

**Comment by sehraf** [comment]
Interesting idea, though this wouldn't fix the "cannot (architectural) chroot anymore" problem, would it?

**Comment by Popolon** [comment]
they are no more needed. Instead use qemu-user-static that is in Extra, and optionnaly qemu-user-static-binfmt.
