### ISSUE TITLE
Modules install path does not match kernel

### ISSUE THREAD

**Issue by a-v-s** [sehraf/riscv-arch-image-builder#19]
The installed kernel identifies at `5.18.0-rc1`
```
[root@licheerv xradio]# uname   -r
5.18.0-rc1
```
while the modules are installed in 

`/usr/lib/modules/5.18.0-AllWinnerD1-Smaeul`

**Comment by sehraf** [comment]
What? This is till an issue? It was supposed to be fixed by #11 
Apparently i'm ~~too stupid~~ unable to fix this consistently.

**Comment by sehraf** [comment]
Should be fixed by 5c450da98d578617781ae13f9d2b0850a61b21c4
