### ISSUE TITLE
Unable to bring up wireless interface

### ISSUE THREAD

**Issue by aarobc** [sehraf/riscv-arch-image-builder#27]
Using the most recent artifact (https://github.com/sehraf/riscv-arch-image-builder/actions/runs/3767716130) on the Mango-Pi pro (pink one).

The wireless interface is being detected:
```
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
4: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 94:a4:08:df:a9:f7 brd ff:ff:ff:ff:ff:ff
```

But when I try to bring it up, no errors, but it still shows as `DOWN`:

```
[root@licheerv ~]# ip link set wlan0 up
[root@licheerv ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
4: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 94:a4:08:df:a9:f7 brd ff:ff:ff:ff:ff:ff
```

Any guidance or investigation into this issue would be appreciated. Also, it appears that the base install lacks `wpa_supplicant` out of the box so I'm not sure how I'm supposed to even connect once I finally do get the interface up.

**Comment by sehraf** [comment]
Did you try to actually connect to a wifi network?
You cannot "magically" turn on wifi and expect it to connect to anything on it own :smile: 
https://wiki.archlinux.org/title/Network_configuration/Wireless

**Comment by gsadams** [comment]
As [aarobc](https://github.com/aarobc) mentioned, there don't seem to be any wireless config tools included in this build. There's no `iw` or other tool that's mentioned in that archlinux wiki page, so there doesn't appear to be any way to bring up the interface, and without that, there's no way to download the needed packages. ;)

I appreciate the work you've done to get us this far. But do you have a suggestion about how to bring up the wireless interface with the artifacts you've built? I'm using a Lichee RV with its dock, so I have no ethernet.

**Comment by gsadams** [comment]
Yeah, I was thinking I might need to pick up a USB ethernet adapter. 😄 This is my first Arch machine, so I'm still bootstrapping myself.

Thanks for the tips, and for making this image builder!
