### ISSUE TITLE
LSD display using

### ISSUE THREAD

**Issue by GorINIch73** [sehraf/riscv-arch-image-builder#9]
Thank you very much for your work!
Tell me how you can connect the LSD display using a standard native Adapter board 5 inc?
I saw DTS for 86 in the kernel, it should work with LCD, but it didn't work for me.
How to configure the bootloader?
Thank you!

**Comment by sehraf** [comment]
I have no such display to test anything.

If you need extra kernel compile option, have look [here](https://github.com/sehraf/riscv-arch-image-builder/blob/main/1_compile.sh#L141-L198).
For kernel runtime  parameter, see [here](https://github.com/sehraf/riscv-arch-image-builder/blob/main/2_create_sd.sh#L100) or [here](https://github.com/sehraf/riscv-arch-image-builder/blob/main/1_compile.sh#L104)
The DTB is defines [here](https://github.com/sehraf/riscv-arch-image-builder/blob/main/1_compile.sh#L89)

**Comment by GorINIch73** [comment]
Thank you!
